### ISSUE TITLE
self.writer.add_scalar("train/cost",cost, up, wall_time) throws exception, need to remove wall_time argument

### ISSUE THREAD

**Issue by stribizhev** [ufal/marian-tensorboard#2]
This issue started appearing quite recently, before, it was working well. This is the exception (note I modified the script a bit to just accommodate for a different project model structure):

```
Traceback (most recent call last):
  File "/marian/build/marian-tensorboard/tb_log_parser.py", line 207, in <module>
    m.update_loop()
  File "/marian/build/marian-tensorboard/tb_log_parser.py", line 149, in update_loop
    up = self.parse_train(line)
  File "/marian/build/marian-tensorboard/tb_log_parser.py", line 65, in parse_train
    self.writer.add_scalar("train/epoch",ep,up, wall_time)
TypeError: add_scalar() takes from 3 to 4 positional arguments but 5 were given
```

Basically, the fix is to remove the fourth argument, `wall_time`, rewrite all lines like `self.writer.add_scalar("train/cost",cost, up, wall_time)` to

     self.writer.add_scalar("train/cost",cost, up)

It seems to work, but I wonder if the fix I came up with is correct. BTW, the [TensorBoardX documentation](https://tensorboardx.readthedocs.io/en/latest/tutorial.html) also shows an example with just 3 arguments to `add_scalar` method.

**Comment by Gldkslfmsd** [comment]
https://tensorboardx.readthedocs.io/en/latest/tensorboard.html?highlight=time#tensorboardX.SummaryWriter.add_scalar

wall_time is optional argument.

**Comment by stribizhev** [comment]
I have seen that documentation part, and it does not explain why the exception is thrown when the optional argument is provided. Thus, no idea what is happening, I hope that removing the argument nothing bad happens. Actually, I do not see any difference and that is probably a good sign.
